name: Context Examples

on: ["push"]

jobs:
  my-context:
    runs-on: ubuntu-latest
    env:
      MY_ACTION: ${{ github.action }}
    steps:
      - name: "My Step"
        run: echo "Hello! $MY_ACTION"
        